language: python
python:
    - "2.7"
    - "3.4"
cache: apt
before_install:
    - sudo apt-get -qq  update -y
    - sudo apt-get install -y liblapack-dev gfortran
# command to install deps
install:
    - pip install -r requirements.txt
    - pip install pylint

script:
    - pylint $(find -name '*.py')
    - py.test
